name: yummy
description: Yummy is a food platform for customers to order food from a wide variety of restaruants

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  uuid: ^4.5.1
  intl: ^0.20.1
  shared_preferences: ^2.3.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  shared_preferences_platform_interface: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter   

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  build_runner: ^2.4.13
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/restaurants/
    - assets/profile_pics/
    - assets/food/
